# .travis.yml
language: node_js
git:
  depth: 1
matrix:
  include:
  - node_js: '6.3'
    script:
      - npm run travis
notifications:
  email: false
deploy:
  - provider: npm
    email: jim@vigour.io
    on:
      branch: master
      tags: true
